// Target generators (§5.8, §14, adapters/A01-A04). Each returns {relativePath: text}.
// Library field names are labelled "Not verified against the pinned version" inside the generated files until a run
// checks them against the version it pins (R4, §14.1 rule 4). The versions pinned by the adapter verification run are
// listed in VERIFIED below and in adapters/README.md; a generator whose target was not compiled keeps the Not verified label.
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const colorKey = (n) => camel(n.replace(/^color-/, ''));
const lower = (ns) => ns.toLowerCase();
const pascal = (ns) => ns.charAt(0).toUpperCase() + ns.slice(1).toLowerCase();
const isColor = (t) => t.type === 'color';
// Colour literal -> {r,g,b,a} (0-255). tokens.json colours are #rrggbb, #rrggbbaa or the keyword "transparent".
const rgbaOf = (h) => {
  if (h === 'transparent') return { r: 0, g: 0, b: 0, a: 0 };
  const s = String(h).replace(/^#/, '');
  return { r: parseInt(s.slice(0, 2), 16), g: parseInt(s.slice(2, 4), 16), b: parseInt(s.slice(4, 6), 16), a: s.length === 8 ? parseInt(s.slice(6, 8), 16) : 255 };
};
const hex2 = (n) => n.toString(16).padStart(2, '0');
const hexA = (h) => { const c = rgbaOf(h); return hex2(c.a) + hex2(c.r) + hex2(c.g) + hex2(c.b); }; // AARRGGBB
const px = (v) => (typeof v === 'number' ? v : parseFloat(v));
const round3 = (x) => Math.round(x * 1000) / 1000;
const dnum = (x) => (Number.isInteger(x) ? `${x}.0` : `${round3(x)}`); // Dart/Swift double literal
const HEADER = (c) => `${c} GENERATED by tools/build.mjs from assets/tokens.json. Do not edit by hand (R1).`;
const NOT_VERIFIED = (c) => `${c} Library field names: Not verified against the pinned version (R4). Check them in Sprint 0 and record the result as A-nn.`;
// Versions the adapter verification run type-checked / compiled against (adapters/A01-A04). Upgrading a library = re-run.
const VERIFIED = {
  antd: 'antd 6.6.5 (tsc --strict, adapters/A01-antd-v6.md)',
  mui: '@mui/material 7.3.11 (tsc --strict, adapters/A02-mui-v7.md)',
  tailwind: 'tailwindcss 4.3.3 (@tailwindcss/cli compile, adapters/A03-shadcn-tailwind4.md)',
  shadcn: 'shadcn/ui new-york-v4 contract + tailwindcss 4.3.3 (compile, adapters/A03-shadcn-tailwind4.md)',
  figma: '@figma/plugin-typings 1.141.0 VariableScope (tsc --strict)',
};
const VERIFIED_LINE = (c, k) => `${c} Library field names verified against ${VERIFIED[k]}. Re-verify on every library upgrade (R4).`;

function modeName(m) { const [b, t] = m.split('/'); return camel(`${b}-${t}`.toLowerCase().replace(/[^a-z0-9-]/g, '-')); }
// Relative luminance of the base surface decides light/dark per mode (same rule as tokens.css color-scheme).
function isDarkMode(model, m) {
  const v = model.byName['color-structure-surface-base']?.raw[m];
  if (!v) return false;
  const { r, g, b } = rgbaOf(v);
  return (r + g + b) / 3 < 128;
}
const themeOf = (m) => m.split('/')[1];
const has = (model, n) => Boolean(model.byName[n]);
const firstOf = (model, ...names) => names.find((n) => has(model, n));
// Minimum touch target (STD-4). Never below 44.
const touchMin = (model) => Math.max(44, px(model.byName['target-min-touch']?.raw[model.modes.color[0]] ?? 44));
const densityVal = (model, n, d) => { const t = model.byName[n]; if (!t) return undefined; return t.raw[d ?? model.axes.density[0]] ?? t.raw[model.modes.color[0]]; };

// ---------------- Flutter (A04: ThemeExtension, typed, copyWith + lerp; Material 3 ThemeData) ----------------
function flutter(model, { ns }) {
  const n = lower(ns), P = pascal(ns);
  const colors = model.list.filter(isColor);
  const fields = colors.map((t) => colorKey(t.name));
  const consts = model.modes.color.map((m) => `  static const ${modeName(m)} = ${P}Colors(\n${colors.map((t) => `    ${colorKey(t.name)}: Color(0x${hexA(t.raw[m])}),`).join('\n')}\n  );`).join('\n\n');
  const colorsDart = `${HEADER('//')}
${NOT_VERIFIED('//')}
import 'package:flutter/material.dart';

/// Typed colour tokens for every brand × theme mode (§14.3 rule 3). Read colours only from this extension.
@immutable
class ${P}Colors extends ThemeExtension<${P}Colors> {
  const ${P}Colors({\n${fields.map((f) => `    required this.${f},`).join('\n')}\n  });

${fields.map((f) => `  final Color ${f};`).join('\n')}

${consts}

  static const Map<String, ${P}Colors> modes = {\n${model.modes.color.map((m) => `    '${m}': ${modeName(m)},`).join('\n')}\n  };

  /// The extension registered on the nearest Theme. Throws if ${P}Theme.of(...) was not used to build the ThemeData.
  static ${P}Colors of(BuildContext context) => Theme.of(context).extension<${P}Colors>()!;

  @override
  ${P}Colors copyWith({${fields.map((f) => `Color? ${f}`).join(', ')}}) => ${P}Colors(\n${fields.map((f) => `    ${f}: ${f} ?? this.${f},`).join('\n')}\n  );

  @override
  ${P}Colors lerp(covariant ThemeExtension<${P}Colors>? other, double t) {
    if (other is! ${P}Colors) return this;
    return ${P}Colors(\n${fields.map((f) => `      ${f}: Color.lerp(${f}, other.${f}, t)!,`).join('\n')}\n    );
  }
}
`;
  const num = model.list.filter((t) => ['dimension', 'number', 'duration', 'fontWeight'].includes(t.type) && !t.varies.includes('density') && !t.varies.includes('theme'));
  const m0 = model.modes.color[0];
  const fw = (v) => `FontWeight.w${Math.min(900, Math.max(100, Math.round(px(v) / 100) * 100))}`; // FontWeight.wNNN exists on every Flutter 3.x
  const lit = (t) => {
    const v = t.raw[m0];
    if (t.type === 'duration') return `Duration(milliseconds: ${px(v)})`;
    if (t.type === 'fontWeight') return fw(v);
    if (typeof v === 'number') return dnum(v);
    return `'${v}'`;
  };
  const dens = model.list.filter((t) => t.varies.includes('density'));
  const tokensDart = `${HEADER('//')}
import 'package:flutter/widgets.dart';

/// Non-colour tokens (spacing, radius, type, motion, layout, z, opacity). Logical pixels.
abstract final class ${P}Tokens {
${num.map((t) => `  static const ${camel(t.name)} = ${lit(t)};`).join('\n')}
${model.list.filter((t) => t.type === 'fontFamily' && !String(t.raw[m0]).startsWith('{')).map((t) => `  static const ${camel(t.name)} = '${Array.isArray(t.raw[m0]) ? t.raw[m0][0] : t.raw[m0]}';`).join('\n')}
}

/// Density mode values (§5.9). compact is never active in touch mode (STD-4).
class ${P}Density {
  const ${P}Density({${dens.map((t) => `required this.${camel(t.name)}`).join(', ')}});
${dens.map((t) => `  final double ${camel(t.name)};`).join('\n')}
${model.axes.density.map((d) => `  static const ${d} = ${P}Density(${dens.map((t) => `${camel(t.name)}: ${dnum(px(t.raw[d]))}`).join(', ')});`).join('\n')}
}

/// Elevation per brand × theme.
abstract final class ${P}Elevation {
${model.list.filter((t) => t.type === 'shadow' && t.name !== 'elevation-0' && t.layer === 'semantic').map((t) => `  static const Map<String, List<BoxShadow>> ${camel(t.name)} = {\n${model.modes.color.map((m) => `    '${m}': [${(Array.isArray(t.raw[m]) ? t.raw[m] : []).map((l) => `BoxShadow(color: Color(0x${hexA(l.color)}), offset: Offset(${dnum(l.offsetX)}, ${dnum(l.offsetY)}), blurRadius: ${dnum(l.blur)}, spreadRadius: ${dnum(l.spread || 0)})`).join(', ')}],`).join('\n')}\n  };`).join('\n')}
}
`;
  return {
    [`packages/${n}_design/lib/src/tokens/${n}_colors.g.dart`]: colorsDart,
    [`packages/${n}_design/lib/src/tokens/${n}_tokens.g.dart`]: tokensDart,
    [`packages/${n}_design/lib/src/tokens/${n}_theme.g.dart`]: flutterTheme(model, { n, P }),
  };
}

// Material 3 ThemeData (A04). ColorScheme roles come from semantic tokens; surfaceTint is transparent so M3 does not
// re-tint surfaces (the AntD darkAlgorithm problem in Flutter form). TextTheme pins every body/label role >= body (STD-2).
function flutterTheme(model, { n, P }) {
  const m0 = model.modes.color[0];
  const c = (...names) => { const k = firstOf(model, ...names); return k ? `c.${colorKey(k)}` : null; };
  const scheme = [
    ['brightness', `brightness[mode]!`],
    ['primary', c('color-interaction-default')], ['onPrimary', c('color-interaction-on-solid')],
    ['primaryContainer', c('color-interaction-subtle')], ['onPrimaryContainer', c('color-structure-text-primary')],
    ['secondary', c('color-brand-default', 'color-interaction-default')], ['onSecondary', c('color-brand-on', 'color-interaction-on-solid')],
    ['secondaryContainer', c('color-brand-subtle', 'color-interaction-subtle')], ['onSecondaryContainer', c('color-structure-text-primary')],
    ['error', c('color-semantic-critical')], ['onError', c('color-semantic-on-critical')],
    ['errorContainer', c('color-semantic-critical-subtle')], ['onErrorContainer', c('color-semantic-critical-strong')],
    ['surface', c('color-structure-surface-base')], ['onSurface', c('color-structure-text-primary')],
    ['onSurfaceVariant', c('color-structure-text-secondary')],
    ['surfaceContainerLowest', c('color-structure-surface-base')], ['surfaceContainerLow', c('color-structure-surface-raised')],
    ['surfaceContainer', c('color-structure-surface-raised')], ['surfaceContainerHigh', c('color-structure-surface-overlay')],
    ['surfaceContainerHighest', c('color-structure-surface-sunken')],
    ['outline', c('color-structure-border-control')], ['outlineVariant', c('color-structure-border')],
    ['shadow', c('color-structure-shadow')], ['scrim', c('color-structure-scrim')],
    ['inverseSurface', c('color-structure-surface-inverse')], ['onInverseSurface', c('color-structure-text-oninverse')],
    ['surfaceTint', 'const Color(0x00000000)'],
  ].filter(([, v]) => v);
  const g = (k, s) => model.byName[`type-${k}-${s}`]?.raw[m0];
  const role = (...ks) => ks.find((k) => g(k, 'size') != null);
  const ts = (k) => {
    const size = px(g(k, 'size')), line = px(g(k, 'line')), w = g(k, 'weight'), tr = g(k, 'tracking'), fam = g(k, 'family');
    const fams = Array.isArray(fam) ? fam : fam ? [fam] : [];
    const fallback = fams.slice(1).filter((f) => !/^(-|ui-|system-ui$|sans-serif$|serif$|monospace$)/.test(f));
    const ls = tr == null ? null : String(tr).endsWith('em') ? parseFloat(tr) * size : px(tr);
    const parts = [fams[0] ? `fontFamily: '${fams[0]}'` : null, fallback.length ? `fontFamilyFallback: <String>[${fallback.map((f) => `'${f}'`).join(', ')}]` : null,
      `fontSize: ${dnum(size)}`, line ? `height: ${dnum(round3(line / size))}` : null, w != null ? `fontWeight: FontWeight.w${Math.min(900, Math.max(100, Math.round(px(w) / 100) * 100))}` : null,
      ls != null ? `letterSpacing: ${dnum(round3(ls))}` : null].filter(Boolean);
    return `TextStyle(${parts.join(', ')})`;
  };
  const body = role('body');
  // M3 role -> system type role. bodyMedium is the default Text style; bodySmall/labelLarge/labelMedium/labelSmall are body
  // text in M3 components (helper/error text, buttons, tabs, navigation labels, Badge) so none may drop below body (STD-2).
  // type-caption has no M3 role: read it from the generated <NS>Tokens class for genuine supporting text only.
  const textRoles = [
    ['displayLarge', role('display', 'h1')], ['displayMedium', role('display', 'h1')], ['displaySmall', role('h1')],
    ['headlineLarge', role('h1')], ['headlineMedium', role('h2', 'h1')], ['headlineSmall', role('h3', 'h2')],
    ['titleLarge', role('h3', 'h2')], ['titleMedium', role('body-lg', 'body')], ['titleSmall', role('label', 'body')],
    ['bodyLarge', role('body-lg', 'body')], ['bodyMedium', body], ['bodySmall', body],
    ['labelLarge', role('label', 'body')], ['labelMedium', role('label', 'body')], ['labelSmall', body],
  ].filter(([, k]) => k);
  const hTok = model.byName['control-height-md'];
  const tm = touchMin(model);
  const minH = hTok?.varies.includes('density') ? `(density.controlHeightMd < ${dnum(tm)} ? ${dnum(tm)} : density.controlHeightMd)` : dnum(Math.max(tm, px(densityVal(model, 'control-height-md') ?? tm)));
  const noRipple = model.byName['state-layer-pressed-opacity']?.raw[m0] === 0;
  const critStrong = c('color-semantic-critical-strong');
  return `${HEADER('//')}
${NOT_VERIFIED('//')}
import 'package:flutter/material.dart';

import '${n}_colors.g.dart';
import '${n}_tokens.g.dart';

/// Material 3 ThemeData per brand × theme mode (adapters/A04-flutter-material3.md).
/// Usage: MaterialApp(theme: ${P}Theme.of('${m0}'), ...). Do not clamp MediaQuery.textScaler below 2.0 (STD-2).
abstract final class ${P}Theme {
  static const Map<String, Brightness> brightness = {
${model.modes.color.map((m) => `    '${m}': Brightness.${isDarkMode(model, m) ? 'dark' : 'light'},`).join('\n')}
  };

  /// Every body/label role is pinned to the system type scale; none is below the body size (STD-2).
  static const TextTheme textTheme = TextTheme(
${textRoles.map(([r, k]) => `    ${r}: ${ts(k)}, // type-${k}`).join('\n')}
  );

  static ThemeData of(String mode, {${P}Density density = ${P}Density.${model.axes.density[0]}}) {
    final c = ${P}Colors.modes[mode];
    if (c == null) throw ArgumentError.value(mode, 'mode', 'unknown brand/theme mode');
    final scheme = ColorScheme(
${scheme.map(([k, v]) => `      ${k}: ${v},`).join('\n')}
    );
    // STD-4: visual minimum = control-height-md (never < ${tm}); hit area is additionally padded to 48 by MaterialTapTargetSize.padded.
    final buttons = ButtonStyle(minimumSize: WidgetStatePropertyAll<Size>(Size(64.0, ${minH})));
    return ThemeData(
      useMaterial3: true,
      colorScheme: scheme,
      textTheme: textTheme,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      visualDensity: VisualDensity.standard,${noRipple ? `\n      splashFactory: NoSplash.splashFactory, // language has no pressed state layer (state-layer-pressed-opacity = 0)` : ''}
      filledButtonTheme: FilledButtonThemeData(style: buttons),
      elevatedButtonTheme: ElevatedButtonThemeData(style: buttons),
      outlinedButtonTheme: OutlinedButtonThemeData(style: buttons),
      textButtonTheme: TextButtonThemeData(style: buttons),
      // Badge text is body text (STD-2): the default 16dp large badge cannot hold it.
      badgeTheme: const BadgeThemeData(largeSize: 24.0),${critStrong ? `
      // Error text uses the text-strength critical token: colorScheme.error as text is < 4.5:1 on dark surfaces (EF-005).
      inputDecorationTheme: InputDecorationThemeData(errorStyle: TextStyle(color: ${critStrong})),` : ''}
      extensions: <ThemeExtension<dynamic>>[c],
    );
  }
}
`;
}

// ---------------- SwiftUI ----------------
function swiftui(model, { ns }) {
  const P = pascal(ns);
  const colors = model.list.filter(isColor);
  const rgba = (h) => { const c = rgbaOf(h); return `Color(.sRGB, red: ${(c.r / 255).toFixed(4)}, green: ${(c.g / 255).toFixed(4)}, blue: ${(c.b / 255).toFixed(4)}, opacity: ${(c.a / 255).toFixed(4)})`; };
  return {
    [`packages/${P}Design/Sources/${P}Design/Tokens/${P}Colors.g.swift`]: `${HEADER('//')}
${NOT_VERIFIED('//')}
import SwiftUI

public struct ${P}Colors: Sendable {
${colors.map((t) => `    public let ${colorKey(t.name)}: Color`).join('\n')}

${model.modes.color.map((m) => `    public static let ${modeName(m)} = ${P}Colors(\n${colors.map((t, i) => `        ${colorKey(t.name)}: ${rgba(t.raw[m])}${i < colors.length - 1 ? ',' : ''}`).join('\n')}\n    )`).join('\n\n')}
}
`,
    [`packages/${P}Design/Sources/${P}Design/Tokens/${P}Tokens.g.swift`]: `${HEADER('//')}
import SwiftUI

public enum ${P}Tokens {
${model.list.filter((t) => ['dimension', 'number', 'duration'].includes(t.type) && !t.varies.length && typeof t.raw[model.modes.color[0]] === 'number').map((t) => `    public static let ${camel(t.name)}: CGFloat = ${t.raw[model.modes.color[0]]}`).join('\n')}
}
`,
  };
}

// ---------------- Jetpack Compose ----------------
function compose(model, { ns }) {
  const P = pascal(ns), n = lower(ns);
  const colors = model.list.filter(isColor);
  return {
    [`packages/${n}-design/src/main/kotlin/${n}/design/tokens/${P}Colors.g.kt`]: `${HEADER('//')}
${NOT_VERIFIED('//')}
package ${n}.design.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class ${P}Colors(
${colors.map((t) => `    val ${colorKey(t.name)}: Color,`).join('\n')}
) {
    companion object {
${model.modes.color.map((m) => `        val ${modeName(m)} = ${P}Colors(\n${colors.map((t) => `            ${colorKey(t.name)} = Color(0x${hexA(t.raw[m]).toUpperCase()}),`).join('\n')}\n        )`).join('\n')}
    }
}
`,
    [`packages/${n}-design/src/main/kotlin/${n}/design/tokens/${P}Tokens.g.kt`]: `${HEADER('//')}
package ${n}.design.tokens

import androidx.compose.ui.unit.dp

object ${P}Tokens {
${model.list.filter((t) => t.type === 'dimension' && !t.varies.length && typeof t.raw[model.modes.color[0]] === 'number').map((t) => `    val ${camel(t.name)} = ${t.raw[model.modes.color[0]]}.dp`).join('\n')}
}
`,
  };
}

// ---------------- Tailwind v4 (@theme inline over the system's CSS variables) ----------------
// Utility name for a colour token: structure/semantic prefixes dropped (bg-surface-base, text-text-primary, bg-critical).
const twColor = (name) => name.replace(/^color-(structure-|semantic-|interaction-)?/, (m, g) => (g === 'interaction-' ? 'interaction-' : ''));
function tailwind(model) {
  const L = model.list;
  const lines = [];
  for (const t of L.filter(isColor)) lines.push(`  --color-${twColor(t.name)}: var(--${t.name});`);
  // --radius-* / --font-* share their names with the system tokens: in @theme inline the utility reads var(--radius-md)
  // directly, and the unlayered system declaration in tokens.css wins over Tailwind's @layer theme copy.
  for (const t of L.filter((t) => /^radius-/.test(t.name))) lines.push(`  --${t.name}: var(--${t.name});`);
  for (const t of L.filter((t) => /^font-/.test(t.name))) lines.push(`  --${t.name}: var(--${t.name});`);
  for (const t of L.filter((t) => /^type-.*-size$/.test(t.name))) {
    const k = t.name.replace(/^type-|-size$/g, '');
    lines.push(`  --text-${k}: var(--${t.name});`);
    if (has(model, `type-${k}-line`)) lines.push(`  --text-${k}--line-height: var(--type-${k}-line);`);
    if (has(model, `type-${k}-weight`)) lines.push(`  --text-${k}--font-weight: var(--type-${k}-weight);`);
    if (has(model, `type-${k}-tracking`)) lines.push(`  --text-${k}--letter-spacing: var(--type-${k}-tracking);`);
  }
  for (const t of L.filter((t) => /^elevation-/.test(t.name))) lines.push(`  --shadow-${t.name.replace('elevation-', 'e')}: var(--${t.name});`);
  // Breakpoints in rem: Tailwind sorts breakpoints by value and its defaults are rem; mixed units sort unreliably.
  for (const t of L.filter((t) => /^bp-/.test(t.name) && t.name !== 'bp-mobile')) lines.push(`  --breakpoint-${t.name.replace('bp-', '')}: ${round3(px(t.raw[model.modes.color[0]]) / 16)}rem;`);
  for (const k of ['standard', 'enter', 'exit']) if (has(model, `motion-easing-${k}`)) lines.push(`  --ease-${k}: var(--motion-easing-${k});`);
  return {
    'assets/tailwind.theme.css': `/* ${HEADER('').trim()} */
/* Tailwind CSS v4 theme. Import after tokens.css. Tailwind's default palette and type scale are reset so only system tokens exist (I3). */
/* inline: utilities read the system variables directly. reference: Tailwind emits no theme variables of its own, so
   --radius-md / --font-sans / --color-interaction-* (same names as system tokens) never become self-references (var cycle). */
/* ${VERIFIED_LINE('', 'tailwind').trim()} */
@theme inline reference {
  --color-*: initial;
  --text-*: initial;
  --spacing: 4px;
${lines.join('\n')}
}
`,
  };
}

// ---------------- Ant Design v6 (A01) ----------------
function antd(model, { ns }) {
  const P = pascal(ns);
  const by = (n, m) => model.byName[n]?.raw[m];
  const out = {};
  const themes = {};
  const d0 = model.axes.density[0];
  const tm = touchMin(model);
  for (const m of model.modes.color) {
    const v = (n) => by(n, m) ?? model.byName[n]?.raw[d0];
    const bodySize = Math.max(16, by('type-body-size', m));
    themes[m] = {
      // algorithm is deliberately NOT darkAlgorithm: it re-derives colorPrimary and breaks contrast proofs (engine finding EF-004).
      // Every derived colour AntD would otherwise compute from the seed (hover/active/border/text) is pinned to a system token.
      token: {
        colorPrimary: v('color-interaction-default'), colorPrimaryHover: v('color-interaction-hover'), colorPrimaryActive: v('color-interaction-pressed'),
        colorPrimaryBorder: v(firstOf(model, 'color-interaction-border', 'color-interaction-default')), colorPrimaryBg: v('color-interaction-subtle'), colorPrimaryBgHover: v('color-interaction-subtle'),
        colorPrimaryText: v('color-interaction-default'), colorPrimaryTextHover: v('color-interaction-hover'), colorPrimaryTextActive: v('color-interaction-pressed'),
        colorLink: v('color-interaction-default'), colorLinkHover: v('color-interaction-hover'), colorLinkActive: v('color-interaction-pressed'),
        colorError: v('color-semantic-critical'), colorErrorText: v('color-semantic-critical-strong'), colorErrorBg: v('color-semantic-critical-subtle'), colorErrorBorder: v('color-semantic-critical'),
        colorErrorHover: v(firstOf(model, 'button-destructive-container-background-hover', 'color-semantic-critical')),
        colorErrorActive: v(firstOf(model, 'button-destructive-container-background-pressed', 'color-semantic-critical')),
        colorWarning: v('color-semantic-warning'), colorWarningText: v('color-semantic-warning-strong'), colorWarningBg: v('color-semantic-warning-subtle'),
        colorSuccess: v('color-semantic-positive'), colorSuccessText: v('color-semantic-positive-strong'), colorSuccessBg: v('color-semantic-positive-subtle'),
        colorInfo: v('color-semantic-info'), colorInfoText: v('color-semantic-info-strong'), colorInfoBg: v('color-semantic-info-subtle'),
        colorTextBase: v('color-structure-text-primary'), colorBgBase: v('color-structure-surface-base'),
        colorText: v('color-structure-text-primary'), colorTextSecondary: v('color-structure-text-secondary'), colorTextTertiary: v('color-structure-text-tertiary'),
        colorTextPlaceholder: v('color-structure-text-placeholder'), colorTextDisabled: v('color-structure-text-disabled'), colorTextLightSolid: v('color-interaction-on-solid'),
        colorBgContainer: v('color-structure-surface-raised'), colorBgLayout: v('color-structure-surface-sunken'), colorBgElevated: v('color-structure-surface-overlay'), colorBgMask: v('color-structure-scrim'),
        colorBorder: v('color-structure-border-control'), colorBorderSecondary: v('color-structure-border'), colorSplit: v('color-structure-border'),
        controlOutline: v('color-focus-ring'), controlOutlineWidth: 2, lineWidthFocus: 2,
        fontFamily: (model.byName['font-sans'] && cssList(by('font-sans', m))), fontFamilyCode: (model.byName['font-mono'] && cssList(by('font-mono', m))),
        // STD-2: AntD derives fontSizeSM = fontSize - 2 (14px). Body text must stay >= 16, so every size token is pinned.
        fontSize: bodySize, fontSizeSM: bodySize, fontSizeLG: by('type-body-lg-size', m), fontSizeXL: by('type-h3-size', m),
        fontSizeHeading1: by('type-h1-size', m), fontSizeHeading2: by('type-h2-size', m), fontSizeHeading3: by('type-h3-size', m), fontSizeHeading4: by('type-body-lg-size', m), fontSizeHeading5: bodySize,
        lineHeight: round3(by('type-body-line', m) / by('type-body-size', m)),
        borderRadius: by('radius-sm', m), borderRadiusSM: by('radius-xs', m), borderRadiusLG: by('radius-md', m), borderRadiusXS: by('radius-xs', m),
        controlHeight: v('control-height-md'), controlHeightSM: v('control-height-sm'), controlHeightLG: v('control-height-lg'),
        lineWidth: by('border-width-thin', m),
        motionDurationFast: `${by('motion-fast-duration', m) / 1000}s`, motionDurationMid: `${by('motion-base-duration', m) / 1000}s`, motionDurationSlow: `${by('motion-slow-duration', m) / 1000}s`,
        zIndexPopupBase: by('z-popover', m) * 20,
        wireframe: false,
      },
      components: {
        // Form explain/feedback text reads token.colorError (antd 6.6.5 form/style), not colorErrorText. colorError as text is
        // 4.25-4.42:1 on dark surfaces (engine finding EF-005), so Form gets the text-strength tokens as component-level overrides.
        Form: { labelFontSize: by('type-label-size', m), verticalLabelPadding: '0 0 4px', colorError: v('color-semantic-critical-strong'), colorWarning: v('color-semantic-warning-strong') },
        Button: { contentFontSizeSM: bodySize, primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none' },
        Table: { cellFontSize: bodySize, cellFontSizeMD: bodySize, cellFontSizeSM: bodySize },
        Tag: { defaultBg: v('color-structure-surface-sunken') },
        Layout: {
          siderBg: v('color-structure-surface-raised'), lightSiderBg: v('color-structure-surface-raised'),
          headerBg: v('color-structure-surface-raised'), headerColor: v('color-structure-text-primary'), bodyBg: v('color-structure-surface-sunken'), footerBg: v('color-structure-surface-sunken'),
          // The collapsible Sider trigger defaults to #002140 / white: pinned so it follows the theme.
          triggerBg: v('color-structure-surface-raised'), triggerColor: v('color-structure-text-primary'),
          lightTriggerBg: v('color-structure-surface-raised'), lightTriggerColor: v('color-structure-text-primary'),
          ...(has(model, 'layout-bar-height') ? { headerHeight: by('layout-bar-height', m) } : {}),
        },
      },
    };
  }
  // STD-4: AntD tokens cannot follow a media query; apply this nested theme when (any-pointer: coarse) matches.
  const touch = {
    token: {
      controlHeight: Math.max(tm, px(densityVal(model, 'control-height-md'))),
      controlHeightSM: Math.max(tm, px(densityVal(model, 'control-height-sm'))),
      controlHeightLG: Math.max(tm, px(densityVal(model, 'control-height-lg'))),
    },
    components: { Layout: { zeroTriggerWidth: tm, zeroTriggerHeight: tm } },
  };
  const id = P.toLowerCase();
  out['adapters/antd/theme.g.ts'] = `${HEADER('//')}
${VERIFIED_LINE('//', 'antd')}
// Usage: <ConfigProvider theme={${id}AntdTheme['${model.modes.color[0]}']}> ... </ConfigProvider>
// antd 6 always emits CSS variables (cssVar is an object {prefix,key}, not a boolean). Leave hashed at its default (true):
// hashed:false leaked tokens between nested ConfigProviders (engine finding EF-006). Never add theme.darkAlgorithm (EF-004).
// Touch (STD-4): nest <ConfigProvider theme={${id}AntdTouch}> when matchMedia('(any-pointer: coarse)').matches (inherit merges).
import type { ThemeConfig } from 'antd';

export type ${P}AntdMode = ${model.modes.color.map((m) => `'${m}'`).join(' | ')};

export const ${id}AntdTheme: Record<${P}AntdMode, ThemeConfig> = ${JSON.stringify(themes, null, 2)};

export const ${id}AntdTouch: ThemeConfig = ${JSON.stringify(touch, null, 2)};
`;
  return out;
}

// ---------------- MUI v7 (A02) ----------------
function mui(model, { ns }) {
  const P = pascal(ns);
  const schemes = {};
  for (const m of model.modes.color) {
    const v = (n) => model.byName[n]?.raw[m];
    schemes[m] = {
      palette: {
        // mode drives MUI's own derived values (action.*, divider fallbacks, getContrastText): it must match the surface.
        mode: isDarkMode(model, m) ? 'dark' : 'light',
        primary: { main: v('color-interaction-default'), dark: v('color-interaction-pressed'), contrastText: v('color-interaction-on-solid') },
        error: { main: v('color-semantic-critical'), contrastText: v('color-semantic-on-critical') },
        warning: { main: v('color-semantic-warning'), contrastText: v('color-semantic-on-warning') },
        success: { main: v('color-semantic-positive'), contrastText: v('color-semantic-on-positive') },
        info: { main: v('color-semantic-info'), contrastText: v('color-semantic-on-info') },
        text: { primary: v('color-structure-text-primary'), secondary: v('color-structure-text-secondary'), disabled: v('color-structure-text-disabled') },
        background: { default: v('color-structure-surface-base'), paper: v('color-structure-surface-raised') },
        divider: v('color-structure-border'),
      },
    };
  }
  const m0 = model.modes.color[0];
  const by = (n) => model.byName[n]?.raw[m0];
  const typ = (k) => ({ fontSize: `${by(`type-${k}-size`)}px`, lineHeight: `${by(`type-${k}-line`)}px`, fontWeight: by(`type-${k}-weight`) });
  const id = P.toLowerCase();
  const noRipple = model.byName['state-layer-pressed-opacity']?.raw[m0] === 0;
  const target = { minWidth: 'var(--target-current)', minHeight: 'var(--target-current)' };
  const bodyFont = { fontSize: `${Math.max(16, by('type-body-size'))}px`, lineHeight: `${by('type-body-line')}px` };
  return {
    'adapters/mui/theme.g.ts': `${HEADER('//')}
${VERIFIED_LINE('//', 'mui')}
// Requires assets/tokens.css on the page: component overrides read var(--target-current), var(--color-focus-ring), ...
import { createTheme } from '@mui/material/styles';

// One scheme per brand × theme mode. MUI's default body2 (14px) and button (14px) violate STD-2 and are overridden.
export const ${id}MuiSchemes = ${JSON.stringify(schemes, null, 2)} as const;

export type ${P}MuiMode = keyof typeof ${id}MuiSchemes;

export function ${id}MuiTheme(mode: ${P}MuiMode = '${m0}') {
  return createTheme({
    cssVariables: true,
    palette: ${id}MuiSchemes[mode].palette,
    shape: { borderRadius: ${by('radius-sm')} },
    typography: {
      // fontSize is MUI's pxToRem base (default 14). Setting it to the body size scales every hard-coded component size by body/14.
      htmlFontSize: 16, fontSize: ${Math.max(16, by('type-body-size'))},
      fontFamily: ${JSON.stringify(cssList(by('font-sans')))},
      h1: ${JSON.stringify(typ('h1'))}, h2: ${JSON.stringify(typ('h2'))}, h3: ${JSON.stringify(typ('h3'))},
      h4: ${JSON.stringify(typ('body-lg'))}, h5: ${JSON.stringify(typ('body'))}, h6: ${JSON.stringify(typ('label'))},
      body1: ${JSON.stringify(typ('body'))}, body2: ${JSON.stringify(typ('body'))},
      subtitle1: ${JSON.stringify(typ('body-lg'))}, subtitle2: ${JSON.stringify(typ('label'))},
      button: { ...${JSON.stringify(typ('label'))}, textTransform: 'none' },
      caption: ${JSON.stringify(typ('caption'))}, overline: { ...${JSON.stringify(typ('caption'))}, textTransform: 'none' },
    },
    components: {
      // Ripple only where the language has a pressed state layer. With disableRipple the focus-visible ring must be styled.
      MuiButtonBase: {
        defaultProps: { disableRipple: ${noRipple} },
        styleOverrides: { root: { '&.Mui-focusVisible': { outline: '2px solid var(--color-focus-ring)', outlineOffset: '2px' } } },
      },
      MuiButton: { styleOverrides: { root: { minHeight: 'max(var(--control-height-md), var(--target-current))', boxShadow: 'none' } } },
      // STD-4: icon-sized controls get the current minimum target (24px pointer, 44px coarse pointer via tokens.css).
      MuiIconButton: { styleOverrides: { root: ${JSON.stringify(target)} } },
      MuiCheckbox: { styleOverrides: { root: ${JSON.stringify(target)} } },
      MuiRadio: { styleOverrides: { root: ${JSON.stringify(target)} } },
      MuiMenuItem: { styleOverrides: { root: { minHeight: 'var(--target-current)' } } },
      // Error text reads palette.error.main, which is < 4.5:1 as text on dark surfaces (EF-005): use the text-strength token.
      // STD-2: helper/error text, chip labels, badge counts and bottom-navigation labels are body text. MUI sizes them from
      // typography.caption or pxToRem(12-13), so they are pinned to the body size.
      MuiFormHelperText: { styleOverrides: { root: { ...${JSON.stringify(bodyFont)}, '&.Mui-error': { color: 'var(--color-semantic-critical-strong)' } } } },
      MuiChip: { styleOverrides: { label: ${JSON.stringify(bodyFont)} } },
      MuiBadge: { styleOverrides: { badge: { fontSize: ${JSON.stringify(bodyFont.fontSize)}, lineHeight: 1, minWidth: 24, height: 24 } } },
      MuiBottomNavigationAction: { styleOverrides: { label: { fontSize: ${JSON.stringify(bodyFont.fontSize)}, '&.Mui-selected': { fontSize: ${JSON.stringify(bodyFont.fontSize)} } } } },
      MuiFormLabel: { styleOverrides: { root: { '&.Mui-error': { color: 'var(--color-semantic-critical-strong)' } } } },
    },
  });
}
`,
  };
}

// ---------------- shadcn/ui (A03) ----------------
function shadcn(model) {
  const map = {
    background: 'color-structure-surface-base', foreground: 'color-structure-text-primary',
    card: 'color-structure-surface-raised', 'card-foreground': 'color-structure-text-primary',
    popover: 'color-structure-surface-overlay', 'popover-foreground': 'color-structure-text-primary',
    primary: 'color-interaction-default', 'primary-foreground': 'color-interaction-on-solid',
    secondary: 'color-structure-surface-sunken', 'secondary-foreground': 'color-structure-text-primary',
    muted: 'color-structure-surface-sunken', 'muted-foreground': 'color-structure-text-secondary',
    accent: 'color-interaction-subtle', 'accent-foreground': 'color-structure-text-primary',
    destructive: 'color-semantic-critical', 'destructive-foreground': 'color-semantic-on-critical',
    border: 'color-structure-border', input: 'color-structure-border-control', ring: 'color-focus-ring',
    'chart-1': 'chart-cat-1', 'chart-2': 'chart-cat-2', 'chart-3': 'chart-cat-3', 'chart-4': 'chart-cat-4', 'chart-5': 'chart-cat-5',
    sidebar: 'color-structure-surface-raised', 'sidebar-foreground': 'color-structure-text-primary', 'sidebar-primary': 'color-interaction-default',
    'sidebar-primary-foreground': 'color-interaction-on-solid', 'sidebar-accent': 'color-interaction-subtle', 'sidebar-accent-foreground': 'color-structure-text-primary',
    'sidebar-border': 'color-structure-border', 'sidebar-ring': 'color-focus-ring',
  };
  const present = Object.entries(map).filter(([, v]) => has(model, v));
  // shadcn's text scale -> system type roles. text-base/lg/xl/2xl must exist because tailwind.theme.css resets --text-*.
  // text-xs is used by Badge, sidebar group labels and menu shortcuts: status/label text is body text (STD-2), so text-xs also
  // maps to body. Genuine supporting text uses text-caption from tailwind.theme.css.
  const textMap = [['xs', 'type-body-size'], ['sm', 'type-body-size'], ['base', 'type-body-size'],
    ['lg', firstOf(model, 'type-body-lg-size', 'type-body-size')], ['xl', firstOf(model, 'type-h3-size', 'type-body-lg-size')],
    ['2xl', firstOf(model, 'type-h2-size', 'type-h3-size')], ['3xl', firstOf(model, 'type-h1-size', 'type-h2-size')]].filter(([, t]) => t);
  const textLines = textMap.flatMap(([k, t]) => { const r = t.replace(/^type-|-size$/g, ''); return [`  --text-${k}: var(--${t});`, ...(has(model, `type-${r}-line`) ? [`  --text-${k}--line-height: var(--type-${r}-line);`] : [])]; });
  const shadowMap = [['xs', 'elevation-1'], ['sm', 'elevation-1'], ['md', 'elevation-2'], ['lg', firstOf(model, 'elevation-3', 'elevation-2')]].filter(([, t]) => t && has(model, t));
  const dark = [...new Set(model.modes.color.filter((m) => isDarkMode(model, m)).map(themeOf))];
  // tokens.css applies the first theme at :root when no data-theme is set, so a dark default theme also matches there.
  const defaultDark = isDarkMode(model, model.modes.color[0]);
  const darkSel = dark.length ? [...(defaultDark ? [':root:not([data-theme])', ':root:not([data-theme]) *'] : []), ...dark.flatMap((t) => [`[data-theme="${t}"]`, `[data-theme="${t}"] *`])].join(', ') : ':not(*)';
  return {
    'adapters/shadcn/shadcn.css': `/* ${HEADER('').trim()} */
/* shadcn/ui variable contract mapped to system tokens. Import AFTER assets/tailwind.theme.css and INSTEAD OF the
   :root/.dark/@theme inline blocks of shadcn's globals.css. Theme switching stays on [data-theme] (tokens.css), not .dark. */
/* ${VERIFIED_LINE('', 'shadcn').trim()} */

/* dark: utilities in shadcn components follow the system's dark themes (${dark.join(', ') || 'none'}), not .dark / prefers-color-scheme. */
@custom-variant dark (&:where(${darkSel}));

:root {
${present.map(([k, v]) => `  --${k}: var(--${v});`).join('\n')}
  --radius: var(--radius-md);
}

@theme inline {
  /* STD-2: shadcn components default to text-sm (14px) and text-xs (12px, Badge). Both map to the body token so no body text renders below 16px. */
${textLines.join('\n')}
${present.map(([k]) => `  --color-${k}: var(--${k});`).join('\n')}
  /* tailwind.theme.css resets --color-*; shadcn still uses text-white (destructive) and bg-black/50 (overlays). */
  --color-white: var(--color-semantic-on-critical);
  --color-black: var(--${firstOf(model, 'color-structure-shadow', 'color-structure-surface-inverse')});
${shadowMap.map(([k, t]) => `  --shadow-${k}: var(--${t});`).join('\n')}
}

/* STD-4: shadcn sizes (h-8/h-9/size-9 = 32-36px) are below the touch minimum. --target-current is 44px on coarse pointers. */
@layer base {
  [data-slot="button"], [data-slot="toggle"], [data-slot="select-trigger"], [data-slot="input"], [data-slot="tabs-trigger"] {
    min-height: var(--target-current);
  }
  [data-slot="button"]:where([data-size="icon"], [data-size^="icon-"]) { min-width: var(--target-current); }
}
`,
  };
}

// ---------------- Design tool variables (§14A, V18) ----------------
function figma(model, { brief }) {
  const theme = model.axes.theme, brands = model.axes.brand;
  const maxModes = brief?.targets?.design_tool_limits?.max_modes ?? 4;
  const brandSeparate = theme.length * brands.length > maxModes;
  const path = (n) => n.replace(/^color-/, 'color/').replace(/-/g, '/');
  const prim = [];
  for (const [fam, ramps] of Object.entries(model.tokens.primitive.color)) {
    for (const [pol, steps] of Object.entries(ramps)) {
      if (steps.$value) { prim.push({ name: `primitive/${fam}/${pol}`, token: `primitive.color.${fam}.${pol}`, type: 'COLOR', scopes: [], values: { default: steps.$value } }); continue; }
      for (const [s, t] of Object.entries(steps)) prim.push({ name: `primitive/${fam}/${pol}/${s}`, token: `primitive.color.${fam}.${pol}.${s}`, type: 'COLOR', scopes: [], values: { default: t.$value } });
    }
  }
  // Semantic colours alias primitives; component colours alias the semantic variable (or carry a literal such as transparent).
  const aliasOf = (ref) => {
    if (typeof ref !== 'string' || !/^\{[^{}]+\}$/.test(ref)) return { value: ref };
    const p = ref.slice(1, -1);
    if (p.startsWith('primitive.color.')) return { alias: p.replace('primitive.color.', 'primitive/').replace(/\./g, '/') };
    if (p.startsWith('semantic.')) return { alias: path(p.slice(9)) };
    return { alias: p.replace(/\./g, '/') };
  };
  const colorVars = model.list.filter(isColor).map((t) => {
    const tok = model.tokens[t.layer]?.[t.name];
    const values = {};
    const modesKeys = brandSeparate ? theme.map((th) => `${brands[0]}/${th}`) : model.modes.color;
    for (const m of modesKeys) { const ref = tok?.$extensions?.ds?.modes?.[m] ?? tok?.$value ?? t.raw[m]; values[brandSeparate ? m.split('/')[1] : m] = aliasOf(ref); }
    return { name: path(t.name), token: t.name, type: 'COLOR', scopes: scopesFor(t.name, 'COLOR'), values };
  });
  const sizeVars = model.list.filter((t) => t.type === 'dimension' && typeof Object.values(t.raw)[0] === 'number').map((t) => ({
    name: t.name.replace(/-/g, '/'), token: t.name, type: 'FLOAT', scopes: scopesFor(t.name, 'FLOAT'),
    values: t.varies.includes('density') ? Object.fromEntries(model.axes.density.map((d) => [d, t.raw[d]])) : Object.fromEntries(model.axes.density.map((d) => [d, Object.values(t.raw)[0]])),
  }));
  const collections = [
    { name: 'primitive', modes: ['default'], hidden_from_publishing: true, variables: prim },
    { name: 'color', modes: brandSeparate ? theme : model.modes.color, hidden_from_publishing: false, variables: colorVars },
    { name: 'size', modes: model.axes.density, hidden_from_publishing: false, variables: sizeVars },
  ];
  return { 'design-tool/variables.json': JSON.stringify({ tool: brief?.targets?.design_tool || 'figma', scopes_verified_against: VERIFIED.figma, collections }, null, 2) };
}
// Figma VariableScope values (verified against @figma/plugin-typings). ALL_SCOPES is never combined with another scope.
function scopesFor(n, type) {
  if (type === 'COLOR') return colorScopes(n);
  if (/^space-/.test(n)) return ['GAP', 'WIDTH_HEIGHT'];
  if (/^radius-/.test(n)) return ['CORNER_RADIUS'];
  if (/^type-.*-size$/.test(n)) return ['FONT_SIZE'];
  if (/^type-.*-line$/.test(n)) return ['LINE_HEIGHT'];
  if (/^border-width/.test(n)) return ['STROKE_FLOAT'];
  if (/^material-blur/.test(n)) return ['EFFECT_FLOAT'];
  if (/^(control-height|layout|avatar|icon|target)-/.test(n)) return ['WIDTH_HEIGHT'];
  if (/^bp-/.test(n)) return []; // breakpoints are not bindable to any field
  return ['ALL_SCOPES'];
}
function colorScopes(n) {
  if (/shadow$/.test(n)) return ['EFFECT_COLOR'];
  if (/(^|-)(text|foreground|label|on|oninverse|placeholder|value)(-|$)/.test(n) || /-on-/.test(n) || /-label-color$/.test(n)) return ['TEXT_FILL'];
  if (/(^|-)(border|focus-ring|ring)(-|$)/.test(n)) return ['STROKE_COLOR'];
  return ['FRAME_FILL', 'SHAPE_FILL'];
}

function cssList(v) { return Array.isArray(v) ? v.map((f) => (/\s/.test(f) && !/^ui-|^system-ui|^-apple/.test(f) ? `"${f}"` : f)).join(', ') : v; }

export const generators = { flutter, swiftui, compose, tailwind, antd, mui, shadcn, figma };
