#!/usr/bin/env node
// Phase 1/9/13: tokens.json -> every generated artefact (R1). Deterministic; writes reports/build-manifest.json with sha256 per file.
// Usage: node tools/build.mjs <outDir> [--targets css,js,flutter,swiftui,compose,tailwind,antd,mui,shadcn,figma] [--ns NS]
import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readJson, writeJson, writeText, flatten, resolveToken, modeKeys, cssValue, isAlias, aliasPath } from './lib/tokens.mjs';
import * as adapters from './adapters/index.mjs';

export function build(outDir, opts = {}) {
  const tokens = readJson(join(outDir, 'assets', 'tokens.json'));
  const brief = existsSync(join(outDir, 'brief.normalized.json')) ? readJson(join(outDir, 'brief.normalized.json')) : {};
  const ns = opts.ns || brief.namespace || 'DS';
  const model = tokenModel(tokens);
  const files = {};
  const emit = (rel, text) => { files[rel] = text.endsWith('\n') ? text : text + '\n'; };

  const wanted = new Set(opts.targets || ['css', 'js', ...defaultTargets(brief)]);
  emit('assets/tokens.css', tokensCss(model));
  if (wanted.has('js')) { emit('assets/tokens.js', tokensJs(model)); emit('assets/tokens.d.ts', tokensDts(model)); }
  for (const [key, gen] of Object.entries(adapters.generators)) {
    if (!wanted.has(key)) continue;
    for (const [rel, text] of Object.entries(gen(model, { ns, brief }))) emit(rel, text);
  }
  const manifest = {};
  for (const rel of Object.keys(files).sort()) {
    writeText(join(outDir, rel), files[rel]);
    manifest[rel] = createHash('sha256').update(files[rel]).digest('hex');
  }
  writeJson(join(outDir, 'reports', 'build-manifest.json'), { engine_version: '1.8.0', files: manifest });
  return manifest;
}

function defaultTargets(brief) {
  const t = brief.targets || {};
  const map = { flutter: 'flutter', swiftui: 'swiftui', compose: 'compose', tailwind: 'tailwind', nextjs: null };
  const out = (t.production_targets || []).map((x) => map[x] ?? x).filter(Boolean);
  for (const a of t.adapters || []) {
    const k = { 'A01-antd-v6': 'antd', 'A02-mui-v7': 'mui', 'A03-shadcn-tailwind4': 'shadcn', 'A04-flutter-material3': 'flutter' }[a];
    if (k) out.push(k);
    if (k === 'shadcn') out.push('tailwind');
  }
  if (t.design_tool && t.design_tool !== 'none') out.push('figma');
  return out;
}

/** Normalised view used by every generator: per-mode literal values, ordered names, axes. */
export function tokenModel(tokens) {
  const mk = modeKeys(tokens);
  const entries = flatten(tokens).filter((e) => e.layer !== 'primitive');
  const list = entries.map((e) => {
    const vb = e.token.$extensions?.ds?.varies_by || [];
    const byColor = {}, byDensity = {};
    if (vb.includes('density')) for (const d of mk.density) byDensity[d] = cssValue(e.token, resolveToken(tokens, e.token, d).value);
    else for (const m of mk.color) byColor[m] = cssValue(e.token, resolveToken(tokens, e.token, m).value);
    const raw = {};
    if (vb.includes('density')) for (const d of mk.density) raw[d] = resolveToken(tokens, e.token, d).value;
    else for (const m of mk.color) raw[m] = resolveToken(tokens, e.token, m).value;
    // component tokens that alias a semantic token are emitted once as var(--semantic) so they follow every mode (R2)
    const cssAlias = e.layer === 'component' && isAlias(e.token.$value) && aliasPath(e.token.$value).startsWith('semantic.') ? `var(--${aliasPath(e.token.$value).slice(9)})` : null;
    return { name: e.name, layer: e.layer, type: e.token.$type, varies: vb, byColor, byDensity, raw, cssAlias, ds: e.token.$extensions?.ds || {} };
  });
  return { tokens, axes: tokens.$metadata.axes, modes: mk, list, byName: Object.fromEntries(list.map((t) => [t.name, t])) };
}

function tokensCss(model) {
  const { axes, modes, list } = model;
  const [b0] = axes.brand, [t0] = axes.theme, [d0] = axes.density;
  const decl = (pairs) => pairs.map(([n, v]) => `  --${n}: ${v};`).join('\n');
  const colorVal = (t, b, th) => t.byColor[`${b}/${th}`];
  const head = ['/* GENERATED by tools/build.mjs from assets/tokens.json. Do not edit by hand (R1). */',
    `/* axes: theme=${axes.theme.join('|')} brand=${axes.brand.join('|')} density=${axes.density.join('|')} */`, ''];
  const blocks = [];
  // :root = default brand × default theme × default density, plus invariant tokens
  const rootPairs = list.filter((t) => !t.cssAlias).map((t) => [t.name, t.varies.includes('density') ? t.byDensity[d0] : colorVal(t, b0, t0)]);
  blocks.push(`:root,\n[data-theme="${t0}"] {\n  color-scheme: ${schemeOf(model, b0, t0)};\n${decl(rootPairs)}\n}`);
  const themed = list.filter((t) => !t.cssAlias && (t.varies.includes('theme') || t.varies.includes('brand')));
  for (const th of axes.theme.slice(1)) {
    blocks.push(`[data-theme="${th}"] {\n  color-scheme: ${schemeOf(model, b0, th)};\n${decl(themed.map((t) => [t.name, colorVal(t, b0, th)]))}\n}`);
  }
  for (const b of axes.brand.slice(1)) {
    const bt = themed.filter((t) => t.varies.includes('brand'));
    blocks.push(`[data-brand="${b}"] {\n${decl(bt.map((t) => [t.name, colorVal(t, b, t0)]))}\n}`);
    for (const th of axes.theme) blocks.push(`[data-brand="${b}"][data-theme="${th}"] {\n${decl(bt.map((t) => [t.name, colorVal(t, b, th)]))}\n}`);
  }
  // theme-varying tokens that also vary by brand must be re-declared for default brand when another brand is active then removed: handled by explicit default-brand blocks
  if (axes.brand.length > 1) {
    const bt = themed.filter((t) => t.varies.includes('brand'));
    for (const th of axes.theme) blocks.push(`[data-brand="${b0}"][data-theme="${th}"] {\n${decl(bt.map((t) => [t.name, colorVal(t, b0, th)]))}\n}`);
  }
  // component tokens alias semantic tokens with var(): declared on every scope that can switch a mode, so nested
  // [data-theme] / [data-brand] regions re-resolve them (a var() is computed where it is declared)
  const aliased = list.filter((t) => t.cssAlias);
  if (aliased.length) blocks.push(`:root,\n[data-theme],\n[data-brand],\n[data-density] {\n${decl(aliased.map((t) => [t.name, t.cssAlias]))}\n}`);
  // RTL: shadows with a horizontal offset mirror (box-shadow has no logical form)
  const shifted = list.filter((t) => t.type === 'shadow' && Object.values(t.raw).some((v) => Array.isArray(v) && v.some((l) => l.offsetX)));
  if (shifted.length) for (const th of axes.theme) {
    const flip = (t) => { const v = t.raw[`${b0}/${th}`]; return Array.isArray(v) ? v.map((l) => `${l.inset ? 'inset ' : ''}${-l.offsetX}px ${l.offsetY}px ${l.blur}px ${l.spread || 0}px ${l.color}`).join(', ') : 'none'; };
    blocks.push(`${th === t0 ? '[dir="rtl"],\n' : ''}[dir="rtl"][data-theme="${th}"],\n[data-theme="${th}"] [dir="rtl"] {\n${decl(shifted.map((t) => [t.name, flip(t)]))}\n}`);
  }
  const dens = list.filter((t) => t.varies.includes('density'));
  for (const d of axes.density) blocks.push(`[data-density="${d}"] {\n${decl(dens.map((t) => [t.name, t.byDensity[d]]))}\n}`);
  // Touch mode (STD-4): minimum hit area and no compact density on coarse pointers
  const comfy = axes.density.includes('comfortable') ? 'comfortable' : axes.density[0];
  blocks.push(`@media (any-pointer: coarse) {\n  :root { --target-current: 44px; }\n  [data-density="compact"] {\n${dens.map((t) => `    --${t.name}: ${t.byDensity[comfy]};`).join('\n')}\n  }\n}`);
  if (model.byName['target-min-extended']) blocks.push(`[data-modality~="glove"],\n[data-modality~="in-motion"] { --target-current: var(--target-min-extended); }`);
  blocks.push(`@media (prefers-reduced-motion: reduce) {\n  :root { --motion-fast-duration: 0ms; --motion-base-duration: 0ms; --motion-slow-duration: 0ms; --motion-stagger-max: 0ms; --state-press-transform: none; }\n}`);
  if (model.byName['material-blur-md'] && Object.values(model.byName['material-blur-md'].byColor).some((v) => v !== '0px')) {
    blocks.push(`@media (prefers-reduced-transparency: reduce) {\n  :root { --material-blur-sm: 0px; --material-blur-md: 0px; --material-blur-lg: 0px; --material-surface-alpha: 1; --color-structure-surface-translucent: var(--color-structure-surface-raised); }\n}`);
  }
  blocks.push(`@media (forced-colors: active) {\n  :root { --material-blur-sm: 0px; --material-blur-md: 0px; --material-blur-lg: 0px; --color-structure-surface-translucent: Canvas; }\n}`);
  return head.join('\n') + blocks.join('\n\n');
}
function schemeOf(model, b, th) {
  const v = model.byName['color-structure-surface-base']?.byColor[`${b}/${th}`];
  if (!v) return 'light';
  const n = parseInt(v.slice(1, 3), 16) + parseInt(v.slice(3, 5), 16) + parseInt(v.slice(5, 7), 16);
  return n / 3 < 128 ? 'dark' : 'light';
}

function tokensJs(model) {
  const { axes, list } = model;
  const values = {};
  for (const m of model.modes.color) values[m] = Object.fromEntries(list.filter((t) => !t.varies.includes('density')).map((t) => [t.name, t.raw[m]]));
  const density = {};
  for (const d of axes.density) density[d] = Object.fromEntries(list.filter((t) => t.varies.includes('density')).map((t) => [t.name, t.raw[d]]));
  return `// GENERATED by tools/build.mjs from assets/tokens.json. Do not edit by hand (R1).
export const axes = ${JSON.stringify(axes)};
export const color = ${JSON.stringify(values, null, 2)};
export const density = ${JSON.stringify(density, null, 2)};
/** Literal value of a token for a mode. */
export function token(name, { brand = axes.brand[0], theme = axes.theme[0], density: d = axes.density[0] } = {}) {
  return (density[d] && name in density[d]) ? density[d][name] : color[\`\${brand}/\${theme}\`][name];
}
/** CSS custom property reference, the only way components read tokens (I3). */
export const cssVar = (name) => \`var(--\${name})\`;
`;
}
function tokensDts(model) {
  return `// GENERATED by tools/build.mjs. Do not edit by hand (R1).
export type TokenName =\n${model.list.map((t) => `  | '${t.name}'`).join('\n')};
export type Theme = ${model.axes.theme.map((t) => `'${t}'`).join(' | ')};
export type Brand = ${model.axes.brand.map((t) => `'${t}'`).join(' | ')};
export type Density = ${model.axes.density.map((t) => `'${t}'`).join(' | ')};
export declare const axes: { theme: Theme[]; brand: Brand[]; density: Density[] };
export declare function token(name: TokenName, mode?: { brand?: Brand; theme?: Theme; density?: Density }): unknown;
export declare const cssVar: (name: TokenName) => string;
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const args = process.argv.slice(2);
  const outDir = args.find((a) => !a.startsWith('--') && !args[args.indexOf(a) - 1]?.startsWith('--'));
  if (!outDir) { console.error('usage: build.mjs <outDir> [--targets a,b] [--ns NS]'); process.exit(2); }
  const ti = args.indexOf('--targets'), ni = args.indexOf('--ns');
  const m = build(outDir, { targets: ti >= 0 ? ['css', 'js', ...args[ti + 1].split(',')] : null, ns: ni >= 0 ? args[ni + 1] : null });
  console.log(`OK build: ${Object.keys(m).length} files\n` + Object.keys(m).map((f) => `  ${f}`).join('\n'));
}
